models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Cat(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    breed = db.Column(db.String(80), nullable=False)
    description = db.Column(db.String(200))
    age_months = db.Column(db.Integer)
    image_url = db.Column(db.String(200), nullable=False)

app.py
from flask import Flask
from models import db
from routes import main_blueprint

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:password@db:5432/postgres'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)

with app.app_context():
    db.create_all()

app.register_blueprint(main_blueprint)

if __name__ == "__main__":
    app.run(host='0.0.0.0')

routes.py
from flask import Blueprint, render_template, request
from models import Cat
from sqlalchemy import or_

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    search = request.args.get('search', '')
    sort_by = request.args.get('sort_by', 'name')

    query = Cat.query.filter(
        or_(
            Cat.breed.ilike(f'%{search}%'),
            Cat.name.ilike(f'%{search}%'),
            Cat.description.ilike(f'%{search}%')
        )
    )

    if sort_by == 'breed':
        query = query.order_by(Cat.breed)
    elif sort_by == 'relevance':
        # Пример сортировки по релевантности, можно использовать текстовое совпадение
        query = query.order_by(Cat.name.contains(search) + Cat.description.contains(search))
    elif sort_by == 'age':
        query = query.order_by(Cat.age_months)
    else:
        query = query.order_by(Cat.name)

    cats = query.paginate(page=page, per_page=5, error_out=False)
    return render_template('index.html', cats=cats.items,
                           next_url=f"/?page={cats.next_num}&search={search}&sort_by={sort_by}",
                           prev_url=f"/?page={cats.prev_num}&search={search}&sort_by={sort_by}")


@main_blueprint.route('/cat/<int:cat_id>')
def cat_detail(cat_id):
    cat = Cat.query.get_or_404(cat_id)
    return render_template('cat_detail.html', cat=cat)

templates/base.html
<!doctype html>
<html>
<head>
    <title>{% block title %}Cat Store{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/cat_detail.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Детали кота</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <h1>{{ cat.name }}</h1>
    <ul>
        <li>Порода: {{ cat.breed }}</li>
        <li>Возраст: {{ cat.age_months }} месяцев</li>
        <li>Описание: {{ cat.description }}</li>
    </ul>
    <img src="{{ cat.image_url }}" alt="Изображение {{ cat.name }}">
    <br>
    <a href="{{ url_for('main.index') }}">Вернуться к списку</a>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Список котов</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <h1>Список котов</h1>
    <form method="get" action="{{ url_for('main.index') }}">
        <input type="text" name="search" placeholder="Поиск" value="{{ request.args.get('search', '') }}">
        <select name="sort_by">
            <option value="name">Имя</option>
            <option value="breed">Порода</option>
            <option value="age">Возраст</option>
            <option value="relevance">Релевантность</option>
        </select>
        <button type="submit">Сортировать</button>
    </form>
    <ul>
        {% for cat in cats.items %}
            <li><a href="{{ url_for('main.cat_detail', cat_id=cat.id) }}">{{ cat.name }}</a> - {{ cat.breed }} - {{ cat.age_months }} месяцев</li>
        {% endfor %}
    </ul>
    <div>
        {% if cats.has_prev %}
            <a href="{{ url_for('main.index', page=cats.prev_num, search=request.args.get('search', ''), sort_by=request.args.get('sort_by', 'name')) }}">Предыдущая</a>
        {% endif %}
        {% if cats.has_next %}
            <a href="{{ url_for('main.index', page=cats.next_num, search=request.args.get('search', ''), sort_by=request.args.get('sort_by', 'name')) }}">Следующая</a>
        {% endif %}
    </div>
</body>
</html>